name: CI

on:
  push:
    branches: ["**"]
  pull_request:

permissions:
  contents: read

jobs:
  nix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix (Determinate Systems)
        uses: DeterminateSystems/nix-installer-action@v13

      - name: Enable Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v6

      - name: Show flake outputs
        run: nix flake show

      - name: Run flake checks (goldens)
        run: nix flake check --show-trace

      - name: Kubeconform validation (networked)
        run: |
          set -euo pipefail
          echo "Deriving manifest packages dynamically"
          nix eval --raw --expr '
            let f = builtins.getFlake (toString ./.);
                sys = builtins.currentSystem;
                pkgs = builtins.getAttr sys f.packages;
                names = builtins.attrNames pkgs;
                filtered = builtins.filter (n: builtins.match "^manifests.*" n != null) names;
            in builtins.concatStringsSep "\n" filtered
          ' | while read -r pkg; do
              echo "Building $pkg";
              nix build ".#$pkg";
              echo "Validating $pkg with kubeconform";
              nix run nixpkgs#yq -- -P '.' result \
                | nix run nixpkgs#kubeconform -- -strict -ignore-missing-schemas -summary -;
            done
